---
title: "Upgrading from crmPack version 1.0"
author: "Wojciech Wójciak, Oliver Boix"
date: "20 June 2023"
output: rmarkdown::html_vignette
bibliography: vignettes.bib  
vignette: >
  %\VignetteIndexEntry{Upgrading from crmPack version 1.0}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteDepends{crmPack}
  \usepackage[utf8]{inputenc}
---

<!-- upgrading_from_the_old_crmPack.Rmd is generated from upgrading_from_the_old_crmPack.Rmd.orig Please edit that file -->



The following vignette describes the changes that were introduced to the `crmPack`
package as a result of the package's refactoring. One row in below tables
represents a single-type, consistent change.

## Class and slot changes

### Naming convention motivation

To be close to common R style guidelines [@advancedR] and use consistent naming conventions within
the `crmPack` package, `CamelCase` notation is used for `class` names, `method` names and constructor function 
names, and `snake_case` notation is used for `slot` names throughout the package.

### New classes



<table class="table" style="font-size: 11px; margin-left: auto; margin-right: auto;">
<thead><tr>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Category</div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Name</div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Comment</div></th>
</tr></thead>
<tbody>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Data </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> DataDA </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Time-to-DLT augmented data. </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Design </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> DADesign </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Design for data augmentation. </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Increments </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> IncrementsHSRBeta </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Limiting further increments using a Hard Safety Rule </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Increments </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> IncrementsRelativeDLTCurrent </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Increments control based on relative differences in terms of DLTs. </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Model </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> DALogisticLogNormal </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Logistic model with bivariate (log) normal prior and data augmentation. </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Model </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> FractionalCRM </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Fractional CRM model. </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Model </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> OneParExpPrior </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Standard CRM with an exponential prior on the power parameter. </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Model </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> OneParLogNormalPrior </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> standard CRM with a normal prior on the log power parameter for the skeleton prior probabilities </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Model </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> ProbitLogNormalRel </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Probit regression model with a bivariate normal prior on the intercept and log slope. </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> nextBest </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> NextBestEWOC </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Next best dose is the highest possible dose subject to overdose control. </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> nextBest </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> NextBestInfTheory </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Next best dose that is based on information theory. </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> nextBest </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> NextBestMinDist </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Next best dose that is based on minimum distance to target probability. </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> nextBest </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> NextBestNCRMLoss </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Next best dose based on NCRM rule and loss function. </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> nextBest </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> NextBestProbMTDLTE </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Next best dose that selects the dose with the highest probability of having a toxicity rate less or equal to the toxicity target. </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> nextBest </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> NextBestProbMTDMinDist </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Next best dose that selects the dose with the highest probability of having a toxicity rate with the smallest distance to the toxicity target. </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Parent model class </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> ModelParamsNormal </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Represents parameters of bivariate normal distribution. </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> SafetyWindow </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> SafetyWindowConst </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Safety window length used when the `gap` should be kept constant. </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> SafetyWindow </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> SafetyWindowSize </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Safety window length based on cohort size. </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Stopping </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> StoppingLowestDoseHSRBeta </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Stopping based on a Hard Safety Rule using the Beta posterior distribution. </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Stopping </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> StoppingMissingDose </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Stopping based on NA returned by next best dose. </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Stopping </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> StoppingMTDCV </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Stopping rule based on precision of MTD which is calculated as the coefficient of variation (CV) of the MTD. </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Stopping </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> StoppingSpecificDose </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Testing a stopping rule at specific dose of the dose grid and not at the next best dose. </td>
  </tr>
</tbody>
</table>



### Renamed classes



<table class="table" style="font-size: 11px; margin-left: auto; margin-right: auto;">
<thead><tr>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Category</div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">New Name</div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Old Name</div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Reason</div></th>
</tr></thead>
<tbody>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Increments </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> IncrementsDoseLevels </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> IncrementsNumDoseLevels </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Harmonization </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Increments </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> IncrementsMin </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> IncrementMin </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Harmonization </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Stopping </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> StoppingMaxGainCIRatio </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> StoppingGstarCIRatio </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> Clarification </td>
  </tr>
</tbody>
</table>



### Renamed slots

Please note that this list might not be exhaustive. Please always check the relevant class documentation for details.



<table class="table" style="font-size: 11px; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Class/Constructor<sup>*</sup></div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Slot/Arg<sup>&dagger;</sup></div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Comment</div></th>
</tr>
<tr>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Name</div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Name</div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">New Name</div></th>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1"></th>
</tr>
</thead>
<tbody>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">CohortSizeDLT</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">cohortSize</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> cohort_size </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">DLTintervals</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> dlt_intervals </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">CohortSizeMax</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">cohortSizeList</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> cohort_size_list </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">CohortSizeMin</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">cohortSizeList</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> cohort_size_list </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">CohortSizeRange</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">cohortSize</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> cohort_size </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">DALogisticLogNormal</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">C_par</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> c_par </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">conditionalPEM</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> cond_pem </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">Design</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">PLcohortSize</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> pl_cohort_size </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">DualEndpointBeta</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">refDoseBeta</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> ref_dose_beta </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">DualEndpointEmax</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">refDoseEmax</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> ref_dose_emax </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">DualEndpointRW</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">useRW1</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> rw1 </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">DualEndpointRW()</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> rw1 </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> replaces `smooth` string </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     text-decoration: line-through;">smooth</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> replaced by `rw1` flag </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">EffFlexi</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">several slots</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> several slots </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> several slot changed, see man page </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">EffFlexi()</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">rw1</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> replaces `smooth` string </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     text-decoration: line-through;">smooth</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> replaced by `rw1` flag </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">Effloglog</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">several slots</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> several slots </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> several slot changed, see man page </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">IncrementsDoseLevels  (IncrementsNumDoseLevels)</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> basis_level </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">IncrementsDoseLevels (IncrementsNumDoseLevels)</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">maxLevels</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> levels </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> change applied also to other dependent classes </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">IncrementsMin (IncrementMin)</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">IncrementsList</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> increments_list </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> change applied also to other dependent classes </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">IncrementsRelativeDLT</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">DLTintervals</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> dlt_intervals </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> change applied also to other dependent classes </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">IncrementsRelativeParts</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">cleanStart</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> clean_start </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> change applied also to other dependent classes </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">dltStart</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> dlt_start </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">McmcOptions</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> rng_kind </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> to be used by Random Number Generator in rJAGS </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> rng_seed </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> to be used by Random Number Generator in rJAGS </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">ModelEff</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     text-decoration: line-through;">dose</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> moved to model class method </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     text-decoration: line-through;">ExpEff</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> moved to model class method and renamed to `efficacy` </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="4"> <span style="     ">NextBestDualEndpoint</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> target_relative </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> replaces `scale` string </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">maxOverdoseProb</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> max_overdose_prob </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     text-decoration: line-through;">scale</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> replaced by `target_relative` flag </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">targetThresh</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> target_thresh </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">NextBestMaxGain</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">DLEDuringTrialtarget</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> prob_target_drt </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">DLEEndOfTrialtarget</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> prob_target_eot </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="4"> <span style="     ">NextBestMaxGainSamples</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">DLEDuringTrialtarget</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> prob_target_drt </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">DLEEndOfTrialtarget</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> prob_target_eot </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">Gstarderive</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> mg_derive </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">TDderive</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> derive </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">NextBestNCRM</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">maxOverdoseProb</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> max_overdose_prob </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">NextBestTD</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">targetDuringTrial</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> prob_target_drt </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">targetEndOfTrial</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> prob_target_eot </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">NextBestTDsamples</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">targetDuringTrial</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> prob_target_drt </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">targetEndOfTrial</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> prob_target_eot </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">StoppingAll</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">stopList</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> stop_list </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">StoppingAny</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">stopList</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> stop_list </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">StoppingList</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">stopList</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> stop_list </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">StoppingMaxGainCIRatio (StoppingGstarCIRatio)</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">targetEndOfTrial</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> prob_target </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">targetRatio</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> target_ratio </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">StoppingTargetBiomarker</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> is_relative </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> replaces `scale` string </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     text-decoration: line-through;">scale</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> replaced by `is_relative` flag </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">StoppingTDCIRatio</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">targetEndOfTrial</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> prob_target </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">targetRatio</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> target_ratio </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">TDDesign</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">PLcohortSize</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> pl_cohort_size </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">TDsamplesDesign</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">PLcohortSize</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> pl_cohort_size </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">TITELogisticLogNormal</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">weightMethod</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> weight_method </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
</tbody>
<tfoot>
<tr>
<td style = 'padding: 0; border:0;' colspan='100%'><sup>*</sup> Class or class' user constructor. In the later case the Name/New Name is followed by ().</td>
</tr>
<tr>
<td style = 'padding: 0; border:0;' colspan='100%'><sup>&dagger;</sup> Slot in case of the class or argument in case of the class' user constructor</td>
</tr>
</tfoot>
</table>



Strikeout indicates that the class/slot was removed.

## Moved `dose` and `prob` Functions from Slots to Methods

Moved `dose` and `prob` functions from model class slots to model class methods.
Example of usage: `dose`/`prob` function as a true dose-DLT/DLT-dose relationship.

### Generate data, define a model and get samples


``` r
library(crmPack)

empty_data <- Data(doseGrid = c(1, 3, 5, 10, 15, 20, 25, 40, 50, 80, 100))
my_model <- LogisticNormal(
  mean = c(-0.85, 1),
  cov = matrix(c(1, -0.5, -0.5, 1), nrow = 2)
)
my_options <- McmcOptions(burnin = 2, step = 2, samples = 20)
my_samples <- mcmc(empty_data, my_model, my_options)
```

### Dose

Here is the example on how the `dose` function can be used in case of different
inputs, i.e. model's parameters samples or in case of a fixed model's parameters
values.


``` r
# Doses reaching a specific target probability of the occurrence of a DLT (equal to 0.3),
# given a particular models and samples.
# Every single dose corresponds to one particular sample in `my_samples`.
dose(0.3, my_model, my_samples)
#>  [1]  1.34841076  0.11025416  0.86730537  1.53660845  1.20567406  0.83567002
#>  [7]  1.64091143  2.28460821  4.52450730  1.44885220  1.58322190  0.02608328
#> [13]  1.21766897  0.39543888  1.28366789  0.73875076 19.61886830  0.60780362
#> [19]  0.05915204  1.29433795

# True dose-DLT relationship.
# Say that -0.8 and 1 are the true values for models parameters alpha0 and alpha1 respectively.
# The `true_dose_fun` takes one argument (target probability of the occurrence of a DLT)
# and computes the corresponding dose, according to the model chosen and given a fixed values
# of the model's parameters.
true_dose_fun <- doseFunction(my_model, alpha0 = -0.8, alpha1 = 1)
true_dose_fun(0.3)
#> [1] 0.9538033
```

### Prob


``` r
# Toxicity probabilities for a given dose (equal to 10), model and samples.
# Every single probability value corresponds to one particular sample in `my_samples`.
prob(10, my_model, my_samples)
#>  [1] 0.93817478 0.22611044 0.99172210 0.73879550 0.86176537 0.02110999
#>  [7] 0.78785107 0.66024799 0.16678261 0.89131170 0.99387321 0.78392448
#> [13] 0.87738055 0.95835853 0.92685442 0.74505590 0.36538941 0.93118090
#> [19] 0.83881343 0.98010014

# True DLT-dose relationship.
# Say that -0.8 and 1 are the true values for models parameters alpha0 and alpha1 respectively.
# The `true_prob_fun` takes one argument (the dose) and computes the corresponding
# toxicity probability, according to the model chosen and given a fixed values
# of the model's parameters.
true_prob_fun <- probFunction(my_model, alpha0 = -0.8, alpha1 = 1)
true_prob_fun(10)
#> [1] 0.8179597
```

## New Random Number Generator settings for the MCMC

The Random Number Generator (RNG) settings used by the JAGS for the MCMC are now
configured solely through the `McmcOptions` class. The RNG settings are:
`RNG type` and the `RNG seed` that corresponds to a given `RNG type`. Find out
details in the help page for the `McmcOptions` class.
Any RNG-related user settings at the R session level (such us those with
`set.seed()`) are ignored by the MCMC sampler.

## New no-argument constructors

To aid software development, new no-argument constructs for all sub-classes of `GeneralModel`, `Increments`, `NextBest` and `Stopping` have been introduced.  The names of these constructors take the form `.Default<classname>`, where `<classname>` is the name of the class being created.

These constructors return valid, but not necessarily contextually sensible, objects of the required class.  One reason the objects returned may not be contextually sensible is that the constructors take no account of any associated `doseGrid`.

Here are some examples of their use:


``` r
.DefaultStoppingAll()
```

If all of the following rules are `TRUE`:

-  ≥ 3 cohorts dosed: If 3 or more cohorts have been treated.


-  P(0.2 ≤ prob(DLE | NBD) ≤ 0.35) ≥ 0.5: If the probability of toxicity at the next best dose is in the range [0.20, 0.35] is at least 0.50.


-  ≥ 20 patients dosed: If 20 or more participants have been treated.





``` r

class_name <- "LogisticNormal"
eval(parse(text = paste0(".Default", class_name, "()")))
```

A logistic log normal model will describe the relationship between dose and toxicity: $$ p(Tox | d) = f(X = 1 | \theta, d) = \frac{e^{\alpha + \beta \cdot d/d^*}}{1 + e^{\alpha + \beta \cdot d/d^*}} $$\n where d* denotes a reference dose.

The prior for &theta; is given by\n$$ \boldsymbol\theta = \begin{bmatrix}\alpha \\ \beta\end{bmatrix}\sim N \left(\begin{bmatrix}-0.85 \\  1.00\end{bmatrix} , \begin{bmatrix} 1.00 & -0.50 \\ -0.50 &  1.00\end{bmatrix} \right) $$

\n\n The reference dose will be 1.00.



## Handling of `NA` or placebo returned as next dose

For consistent handling how the study is stopped and to facilitate analysis of stop reasons in the operation characteristics, the handling of `NA` and placebo returned by `nextBest` methods is changed. In the previous version of `crmPack` stopping for placebo or `NA` returned by a `nextBest` method was handled automatically in the generic `Stopping` method. This is now moved into a new stopping rule `StoppingMissingDose`. As a consequence, the stopping rule `StoppingMissingDose` must be specified for those `nextBest` methods that can return NA, or when placebo is used. Otherwise the simulation may run into an error if the study is not stopped when  `NA` is returned as the next dose. `nextBest` methods that can return `NA` are `NextBestNCRM`, `NextBestNCRMLoss` and `NextBestDualEndpoint`.

## Evaluation of stopping rules at a specific dose

Without further specification, stopping rules are evaluated at the dose returned by the used `nextBest` method. With the new stopping rule `StoppingSpecificDose` it is possible to evaluate stopping rules at any dose. For usage see documentation of `StoppingSpecificDose`.

## Further details in class and methods name changes

### Classes



<table class="table" style="font-size: 11px; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Class/Constructor<sup>*</sup></div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Slot/Arg<sup>&dagger;</sup></div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Comment</div></th>
</tr>
<tr>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Name</div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">New Name</div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Name</div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">New Name</div></th>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1"></th>
</tr>
</thead>
<tbody>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="3"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> ModelLogNormal </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> new parent class for all the models with reference dose and
  bivariate (log) normal prior on the model parameters </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> ModelParamsNormal </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> represents parameters of bivariate normal distribution </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> positive_number </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> to handle strictly positive valued slots
  (e.g. `ref_dose` in many model classes) </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     text-decoration: line-through;">AllModels</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">CohortSizeDLT</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">cohortSize</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> cohort_size </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">DLTintervals</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> intervals </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">CohortSizeMax</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">cohortSizeList</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> cohort_sizes </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">CohortSizeMin</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">cohortSizeList</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> cohort_sizes </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">CohortSizeRange</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">cohortSize</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> cohort_size </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">DALogisticLogNormal</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">C_par</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> c_par </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">conditionalPEM</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> cond_pem </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">Design</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">PLcohortSize</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> pl_cohort_size </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">DualEndpointBeta</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">refDoseBeta</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> ref_dose_beta </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">DualEndpointEmax</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">refDoseEmax</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> ref_dose_emax </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">DualEndpointRW</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">useRW1</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> rw1 </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">DualEndpointRW()</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> rw1 </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> replaces `smooth` string </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     text-decoration: line-through;">smooth</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> replaced by `rw1` flag </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">EffFlexi</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">several slots</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> several slots </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> several slot changed, see man page </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">EffFlexi()</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> rw1 </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> replaces `smooth` string </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     text-decoration: line-through;">smooth</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> replaced by `rw1` flag </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">Effloglog</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">several slots</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> several slots </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> several slot changed, see man page </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">GeneralModel</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> datanames </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> moved from `AllModels` </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> datanames_prior </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">IncrementMin</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> IncrementsMin </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">IncrementsDoseLevels</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> basis_level </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">maxLevels</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> levels </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> change applied also to other dependent classes </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">IncrementsMin</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">IncrementsList</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> increments_list </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> change applied also to other dependent classes </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">IncrementsNumDoseLevels</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> IncrementsDoseLevels </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">IncrementsRelativeDLT</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">DLTintervals</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> intervals </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> change applied also to other dependent classes </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">IncrementsRelativeParts</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">cleanStart</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> clean_start </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> change applied also to other dependent classes </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">dltStart</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> dlt_start </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">McmcOptions</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> rng_kind </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> to be used by Random Number Generator in rJAGS </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> rng_seed </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> to be used by Random Number Generator in rJAGS </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     text-decoration: line-through;">Model</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">ModelEff</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     text-decoration: line-through;">dose</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> moved to model class method </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     text-decoration: line-through;">ExpEff</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> moved to model class method and renamed to `efficacy` </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="4"> <span style="     ">NextBestDualEndpoint</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> target_relative </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> replaces `scale` string </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">maxOverdoseProb</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> max_overdose_prob </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     text-decoration: line-through;">scale</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> replaced by `target_relative` flag </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">targetThresh</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> target_thresh </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">NextBestMaxGain</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">DLEDuringTrialtarget</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> prob_target_drt </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">DLEEndOfTrialtarget</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> prob_target_eot </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="4"> <span style="     ">NextBestMaxGainSamples</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">DLEDuringTrialtarget</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> prob_target_drt </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">DLEEndOfTrialtarget</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> prob_target_eot </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">Gstarderive</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> mg_derive </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">TDderive</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> derive </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">NextBestNCRM</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">maxOverdoseProb</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> max_overdose_prob </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">NextBestTD</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">targetDuringTrial</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> prob_target_drt </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">targetEndOfTrial</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> prob_target_eot </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">NextBestTDsamples</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">targetDuringTrial</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> prob_target_drt </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">targetEndOfTrial</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> prob_target_eot </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">OneParExpNormalPrior</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> OneParLogNormalPrior </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="3"> <span style="     ">OneParLogNormalPrior</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> skel_fun_inv </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">skeletonFun</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> skel_fun </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">skeletonProbs</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> skel_probs </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">OneParLogNormalPrior()</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">doseGrid</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> dose_grid </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="3"> <span style="     ">SafetyWindowConst</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">patientFollow</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> follow </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">patientFollowMin</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> follow_min </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">patientGap</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> gap </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="4"> <span style="     ">SafetyWindowSize</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">patientFollow</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> follow </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">patientFollowMin</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> follow_min </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">patientGap</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> gap </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">sizeIntervals</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> size </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">StoppingAll</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">stopList</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> stop_list </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">StoppingAny</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">stopList</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> stop_list </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="3"> <span style="     ">StoppingGstarCIRatio</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">targetEndOfTrial</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> prob_target </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">targetRatio</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> target_ratio </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> StoppingMaxGainCIRatio </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">StoppingList</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">stopList</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> stop_list </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">StoppingTargetBiomarker</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> is_relative </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> replaces `scale` string </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     text-decoration: line-through;">scale</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> replaced by `is_relative` flag </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">StoppingTDCIRatio</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">targetEndOfTrial</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> prob_target </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">targetRatio</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> target_ratio </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">TDDesign</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">PLcohortSize</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> pl_cohort_size </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">TDsamplesDesign</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">PLcohortSize</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> pl_cohort_size </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">TITELogisticLogNormal</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">weightMethod</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> weight_method </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
</tbody>
<tfoot>
<tr>
<td style = 'padding: 0; border:0;' colspan='100%'><sup>*</sup> Class or class' user constructor. In the later case the Name/New Name is followed by ().</td>
</tr>
<tr>
<td style = 'padding: 0; border:0;' colspan='100%'><sup>&dagger;</sup> Slot in case of the class or argument in case of the class' user constructor</td>
</tr>
</tfoot>
</table>



Strikeout indicates that the class/slot was removed.

### Methods



<table class="table" style="font-size: 11px; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Method</div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Argument</div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Output Changes</div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Comment</div></th>
</tr>
<tr>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Name</div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">New Name</div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Name</div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">New Name</div></th>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1"></th>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1"></th>
</tr>
</thead>
<tbody>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="4"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> doseFunction </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> returns dose computing function for a given model </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> efficacy </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> new generic function </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> probFunction </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> returns probability computing function for a given model </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> update-ModelPseudo </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="3"> <span style="     ">biomLevel</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> xLevel </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> added only for generic, reordered arguments for generic and methods </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     text-decoration: line-through;">dose</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> changed generic and methods </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> biomarker </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> changed generic and methods </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">biomLevel-DualEndpoint</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     text-decoration: line-through;">dose</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">dose</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">prob</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> x </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">gain</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">several arguments</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> several arguments </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> several arguments (generic and methods) changed,
  see man page </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">getEff</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> renamed elements in the list returned </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="3"> <span style="     ">mcmc</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">fromPrior</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> from_prior </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     text-decoration: line-through;">program</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     text-decoration: line-through;">verbose</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="4"> <span style="     ">nextBest-NextBestMaxGain</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> renamed elements in the list returned </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">Effmodel</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> model_eff </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">Effsamples</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> samples_eff </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">SIM</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> in_sim </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="4"> <span style="     ">nextBest-NextBestMaxGainSamples</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> renamed elements in the list returned </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">Effmodel</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> model_eff </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">Effsamples</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> samples_eff </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">SIM</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> in_sim </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="3"> <span style="     ">nextBest-NextBestTD</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">Effmodel</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> model_eff </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">Effsamples</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> samples_eff </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">SIM</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> in_sim </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">nextBest-NextBestTDsamples</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">Effmodel</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> model_eff </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">Effsamples</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> samples_eff </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">size</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> size </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> check </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;vertical-align: top !important;" rowspan="2"> <span style="     ">update-Data</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> check </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">newCohort</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> new_cohort </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">update-DataDA</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> check </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">update-DataDual</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> check </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     ">update-DataParts</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> check </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     text-decoration: line-through;">update-EffFlexi</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> replaced by `update-ModelPseudo` </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     text-decoration: line-through;">update-Effloglog</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> replaced by `update-ModelPseudo` </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     text-decoration: line-through;">update-LogisticIndepBeta</span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> <span style="     "></span> </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;">  </td>
   <td style="text-align:left;width: 6cm; border-left:1px solid;border-right:1px solid;"> replaced by `update-ModelPseudo` </td>
  </tr>
</tbody>
</table>



Strikeout indicates that the method/argument was removed.

## References
