test_that("Package loads without reporting defaults for Data ID and cohort", {
  withr::defer(loadNamespace("crmPack"))
  unloadNamespace("crmPack")
  tmp <- tempfile()
  sink(file(tmp, open = "wt"), type = "message")
  library(crmPack)
  sink(type = "message")
  msg <- readLines(tmp)
  expect_false(any(stringr::str_detect(msg, stringr::fixed("Used default patient IDs!"))))
  expect_false(any(stringr::str_detect(msg, stringr::fixed("Used best guess cohort indices!"))))
})
